FROM omegareizo/ubuntu-node:n18-u22-v1

WORKDIR /tests

COPY ./yarn.lock .
COPY ./package.json .
RUN yarn install --frozen-lockfile

COPY ./public ./public
COPY ./src ./src
COPY ./tests ./tests
COPY ./jest.config.js .
COPY ./nodemon.json .
COPY ./tsconfig.json .
COPY ./tsconfig.build.json .


CMD ["yarn", "test:ci"]